version: "3.7"
services:

  mysql-db:
    container_name: cloud-disk-mysql-db
    build:
      context: .
      dockerfile: ./ci/Dockerfile-mysql
    image: cloud-disk-mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    networks:
      - cloud-disk

  front-envoy:
    container_name: cloud-disk-front-envoy
    build:
      context: .
      dockerfile: ./ci/Dockerfile-frontenvoy
    image: cloud-disk-envoy:latest
    networks:
      - cloud-disk
    ports:
      - "8080:8080"
      - "8443:8443"
      - "8001:8001"


  register-server:
    container_name: cloud-disk-register-server
    build:
      context: .
      dockerfile: ./ci/Dockerfile-app
      target: RegisterServer
    image: cloud-disk-register:latest
    networks:
      - cloud-disk

  login-server:
    container_name: cloud-disk-login-server
    build:
      context: .
      dockerfile: ./ci/Dockerfile-app
      target: LoginServer
    image: cloud-disk-login:latest
    networks:
      - cloud-disk
networks:
  cloud-disk: {}
