version: "3.7"
services:

  mysql-db:
    image: cloud-disk-mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db-root-passwd
      MYSQL_PASSWORD_FILE: /run/secrets/db-root-passwd
    networks:
      - cloud-disk
    secrets:
      - db-passwd
      - db-root-passwd

  front-envoy:
    image: cloud-disk-envoy:latest
    depends_on:
      - "mysql-db"
    networks:
      - cloud-disk
    ports:
      - "8080:8080"
      - "8443:8443"
      - "8001:8001"


  register-server:
    image: cloud-disk-register:latest
    depends_on:
      - "front_envoy"
    networks:
      - cloud-disk

  login-server:
    image: cloud-disk-login:latest
    depends_on:
      - "front_envoy"
    networks:
      - cloud-disk

secrets:
  db-passwd:
    file: secrets/mysql_passwd
  db-root-passwd:
    file: secrets/mysql_passwd
networks:
  cloud-disk: {}
