version: "3.7"
services:

  mysql-db:
    container_name: cloud-disk-mysql-db
    build:
      context: .
      dockerfile: ./ci/Dockerfile-mysql
    image: cloud-disk-mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    networks:
      - cloud-disk
    ports:
      - "3306:3306"
    volumes:
      - /data/mysql/data:/var/lib/mysql

  redis-db:
    container_name: cloud-disk-redis
    image: redis:6.0
    networks:
      - cloud-disk
    ports:
      - "6379:6379"
    volumes:
      - /data/redis/data:/data

  front-envoy:
    container_name: cloud-disk-front-envoy
    build:
      context: .
      dockerfile: ./ci/Dockerfile-frontenvoy
    image: cloud-disk-envoy:latest
    networks:
      - cloud-disk
    volumes:
      - /data/envoy/data:/data
      - /data/envoy/conf/front-envoy.yaml:/etc/front-envoy.yaml
    ports:
      - "8080:8080"
      - "8443:8443"
      - "8001:8001"


  register-server:
    container_name: cloud-disk-register-server
    build:
      context: .
      dockerfile: ./ci/Dockerfile-app
      target: RegisterServer
    image: cloud-disk-register:latest
    networks:
      - cloud-disk

  login-server:
    container_name: cloud-disk-login-server
    build:
      context: .
      dockerfile: ./ci/Dockerfile-app
      target: LoginServer
    image: cloud-disk-login:latest
    networks:
      - cloud-disk

  file-server:
    container_name: cloud-disk-file-server
    build:
      context: .
      dockerfile: ./ci/Dockerfile-app
      target: FileServer
    image: cloud-disk-file:latest
    networks:
      - cloud-disk

networks:
  cloud-disk: {}
