version: "3.7"
services:
  front_envoy:
    build:
      context: .
      dockerfile: Dockerfile-frontenvoy
    networks:
      - cloud-disk
    ports:
      - "8080:8080"
      - "8443:8443"
      - "8001:8001"

  helloworld-server:
    build:
      context: .
      dockerfile: ./ci/Dockerfile
    networks:
      - cloud-disk

networks:
  cloud-disk: {}
