FROM build-os:v1.0 AS builder

RUN set -ex;                                                                      \
    cd usr/src/grpc/build; \
    cmake .. -DCMAKE_BUILD_TYPE=Release \
             -DgRPC_INSTALL=ON \
             -DgRPC_BUILD_TESTS=OFF; \
    make; make install


