ARG BUILD_OS=ubuntu
ARG BUILD_TAG=20.04

FROM ${BUILD_OS}:${BUILD_TAG} AS base

FROM base AS builder

ARG DEBIAN_FRONTEND=noninteractive
ENV TZ=Asia/Shanghai

RUN set -ex;                                                                      \
    apt-get update;  \
    apt-get install -y g++ build-essential autoconf libtool pkg-config openssl libssl-dev git cmake liblog4cplus-dev libhiredis-dev libmysqlclient-dev;                                \
    mkdir -p /usr/src;                                                            \
    cd /usr/src;                                                                  \
    git config --global http.proxy ${HTTP_PROXY};   \
    git clone -b v1.42.0 --depth=1 https://github.com/grpc/grpc.git;  \
    cd /usr/src/grpc; git submodule update --init; \
    mkdir build ; cd build; \
    cmake \
      -DCMAKE_BUILD_TYPE=Release \
      -DgRPC_INSTALL=ON \
      -DgRPC_BUILD_TESTS=OFF \
      -DgRPC_SSL_PROVIDER=package \
      .. ; \
    make; make install;    \
    cd /usr/src;  \
    git clone -b 1.3.3 --depth=1 https://github.com/sewenew/redis-plus-plus.git;  \
    cd redis-plus-plus; mkdir build ; cd build ; cmake -DREDIS_PLUS_PLUS_CXX_STANDARD=11 .. ; make ; make install;  \
    cd /usr/src; \
    git clone -b REL_2_0_5 --depth=1 https://github.com/log4cplus/log4cplus.git;  \
    cd log4cplus; git submodule update --init; mkdir build; cd  build; cmake ..; make ; make install



